# Generated by Django 5.1.1 on 2024-10-06 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persone', '0005_timbratura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=16)),
                ('descrizione', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminato', models.BooleanField(default=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('data_contabile', models.DateField(blank=True, null=True, verbose_name='Data Contabile')),
                ('descrizione', models.CharField(max_length=255)),
                ('entrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entrate_int', models.IntegerField(default=0)),
                ('uscite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uscite_int', models.IntegerField(default=0)),
                ('riferimento_documento', models.CharField(blank=True, max_length=32)),
                ('riga', models.PositiveIntegerField(default=1)),
                ('codice', models.CharField(blank=True, max_length=128)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('anagrafica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persone.persona')),
                ('pagante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='persone.persona')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
