# Generated by Django 5.1.1 on 2024-10-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notizia',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, unique_for_date='creato_il'),
        ),
    ]
