# Generated by Django 5.1.1 on 2024-10-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizie', '0002_alter_notizia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notizia',
            name='titolo',
            field=models.CharField(max_length=255),
        ),
    ]
