# Generated by Django 5.1.1 on 2024-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cell',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codicefiscale',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codicetessera',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comune',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comunenascita',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='datanascita',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='datariltessera',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='entetessera',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='indirizzo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tel',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
