# Generated by Django 5.1.1 on 2024-10-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0002_alter_persona_cell_alter_persona_codicefiscale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cell',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codicefiscale',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codicetessera',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comune',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comunenascita',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='datanascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='datariltessera',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='entetessera',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
