# Generated by Django 5.1.1 on 2024-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0003_alter_persona_cell_alter_persona_codicefiscale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='stato',
            field=models.CharField(choices=[('disattivo', 'Disattivo'), ('attivo', 'Attivo'), ('sospeso', 'Sospeso')], default='attivo', max_length=16),
        ),
    ]
