# Generated by Django 5.1.1 on 2024-10-05 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0004_persona_stato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Ingresso', 'Ingresso'), ('Uscita', 'Uscita')], default='Ingresso', max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbrature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creato_il',),
            },
        ),
    ]
