# Generated by Django 5.1.1 on 2024-10-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0005_timbratura'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='volontario',
            field=models.BooleanField(default=False),
        ),
    ]
