# Generated by Django 5.1.1 on 2024-10-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0008_persona_certmedico_scadenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tutore1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutore1_persona', to='persone.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tutore2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutore2_persona', to='persone.persona'),
        ),
    ]
