# Generated by Django 5.1.1 on 2024-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0009_persona_tutore1_persona_tutore2'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='attivita',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
